// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-6xmeNTVDe_iZB8jLkLQc8v10omufZx8',
    appId: '1:361127524369:web:3f8550eebaa3a8ad05d9b0',
    messagingSenderId: '361127524369',
    projectId: 'todo-app-35b4f',
    authDomain: 'todo-app-35b4f.firebaseapp.com',
    storageBucket: 'todo-app-35b4f.firebasestorage.app',
    measurementId: 'G-7KF2B5FSR2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA42-wqpdwrdKUYK_HX3w99pRIStOCSZaU',
    appId: '1:361127524369:android:adbc47704a97b41d05d9b0',
    messagingSenderId: '361127524369',
    projectId: 'todo-app-35b4f',
    storageBucket: 'todo-app-35b4f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQs-QYNyvbWyE1nt-akEo8CykJdQexIGI',
    appId: '1:361127524369:ios:fbef4cad87e94dd605d9b0',
    messagingSenderId: '361127524369',
    projectId: 'todo-app-35b4f',
    storageBucket: 'todo-app-35b4f.firebasestorage.app',
    iosBundleId: 'com.example.localNotificationss',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQs-QYNyvbWyE1nt-akEo8CykJdQexIGI',
    appId: '1:361127524369:ios:fbef4cad87e94dd605d9b0',
    messagingSenderId: '361127524369',
    projectId: 'todo-app-35b4f',
    storageBucket: 'todo-app-35b4f.firebasestorage.app',
    iosBundleId: 'com.example.localNotificationss',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-6xmeNTVDe_iZB8jLkLQc8v10omufZx8',
    appId: '1:361127524369:web:6cbbe0d221fffcd205d9b0',
    messagingSenderId: '361127524369',
    projectId: 'todo-app-35b4f',
    authDomain: 'todo-app-35b4f.firebaseapp.com',
    storageBucket: 'todo-app-35b4f.firebasestorage.app',
    measurementId: 'G-R2K7PM2H02',
  );
}
